[empty_paren]
match='(:[1])'
rewrite='()'

[empty_brace]
match='{:[1]}'
rewrite='{}'

[empty_bracket]
match='[:[1]]'
rewrite='[]'

[delete_line]
match=':[x\n]'
rewrite=''

[delete_string_content]
match='":[x]"'
rewrite='""'

[delete_empty_paren]
match='()'
rewrite=''

[delete_empty_brace]
match='{}'
rewrite=''
